ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS ticket text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS full_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS group_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS admin_email text NOT NULL DEFAULT '';
